services:
  check:
    image: nixos/nix:2.24
    platform: linux/amd64
    working_dir: /workspace
    volumes:
      - .:/workspace
      - /nix:/nix
    environment:
      - NIX_CONFIG=experimental-features = nix-command flakes
    command: nix flake check

  build:
    image: nixos/nix:2.24
    platform: linux/amd64
    working_dir: /workspace
    volumes:
      - .:/workspace
      - /nix:/nix
    environment:
      - NIX_CONFIG=experimental-features = nix-command flakes
    command: nix build .#image-gnome

  dev:
    image: nixos/nix:2.24
    platform: linux/amd64
    working_dir: /workspace
    volumes:
      - .:/workspace
      - /nix:/nix
    environment:
      - NIX_CONFIG=experimental-features = nix-command flakes
    stdin_open: true
    tty: true
